/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace Pairing {
  export type G1PointStruct = { X: BigNumberish; Y: BigNumberish };

  export type G1PointStructOutput = [X: bigint, Y: bigint] & {
    X: bigint;
    Y: bigint;
  };

  export type G2PointStruct = {
    X: [BigNumberish, BigNumberish];
    Y: [BigNumberish, BigNumberish];
  };

  export type G2PointStructOutput = [
    X: [bigint, bigint],
    Y: [bigint, bigint]
  ] & { X: [bigint, bigint]; Y: [bigint, bigint] };
}

export interface PairingHarnessInterface extends Interface {
  getFunction(
    nameOrSignature: "add" | "generators" | "multiply" | "negate" | "pairing"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "add",
    values: [Pairing.G1PointStruct, Pairing.G1PointStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "generators",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "multiply",
    values: [Pairing.G1PointStruct, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "negate",
    values: [Pairing.G1PointStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "pairing",
    values: [Pairing.G1PointStruct[], Pairing.G2PointStruct[]]
  ): string;

  decodeFunctionResult(functionFragment: "add", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "generators", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "multiply", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "negate", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pairing", data: BytesLike): Result;
}

export interface PairingHarness extends BaseContract {
  connect(runner?: ContractRunner | null): PairingHarness;
  waitForDeployment(): Promise<this>;

  interface: PairingHarnessInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  add: TypedContractMethod<
    [a: Pairing.G1PointStruct, b: Pairing.G1PointStruct],
    [Pairing.G1PointStructOutput],
    "view"
  >;

  generators: TypedContractMethod<
    [],
    [[Pairing.G1PointStructOutput, Pairing.G2PointStructOutput]],
    "view"
  >;

  multiply: TypedContractMethod<
    [p: Pairing.G1PointStruct, scalar: BigNumberish],
    [Pairing.G1PointStructOutput],
    "view"
  >;

  negate: TypedContractMethod<
    [p: Pairing.G1PointStruct],
    [Pairing.G1PointStructOutput],
    "view"
  >;

  pairing: TypedContractMethod<
    [a: Pairing.G1PointStruct[], b: Pairing.G2PointStruct[]],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "add"
  ): TypedContractMethod<
    [a: Pairing.G1PointStruct, b: Pairing.G1PointStruct],
    [Pairing.G1PointStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "generators"
  ): TypedContractMethod<
    [],
    [[Pairing.G1PointStructOutput, Pairing.G2PointStructOutput]],
    "view"
  >;
  getFunction(
    nameOrSignature: "multiply"
  ): TypedContractMethod<
    [p: Pairing.G1PointStruct, scalar: BigNumberish],
    [Pairing.G1PointStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "negate"
  ): TypedContractMethod<
    [p: Pairing.G1PointStruct],
    [Pairing.G1PointStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "pairing"
  ): TypedContractMethod<
    [a: Pairing.G1PointStruct[], b: Pairing.G2PointStruct[]],
    [boolean],
    "view"
  >;

  filters: {};
}
