/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace PilotCurrentRegistry {
  export type HeadStruct = {
    digest: BytesLike;
    value: BigNumberish;
    revision: BigNumberish;
    validFrom: BigNumberish;
    validUntil: BigNumberish;
    publisherEpoch: BigNumberish;
    enabled: boolean;
  };

  export type HeadStructOutput = [
    digest: string,
    value: bigint,
    revision: bigint,
    validFrom: bigint,
    validUntil: bigint,
    publisherEpoch: bigint,
    enabled: boolean
  ] & {
    digest: string;
    value: bigint;
    revision: bigint;
    validFrom: bigint;
    validUntil: bigint;
    publisherEpoch: bigint;
    enabled: boolean;
  };

  export type HeadUpdateStruct = {
    scope: BytesLike;
    digest: BytesLike;
    value: BigNumberish;
    expectedRevision: BigNumberish;
    validFrom: BigNumberish;
    validUntil: BigNumberish;
    enabled: boolean;
    replace: boolean;
  };

  export type HeadUpdateStructOutput = [
    scope: string,
    digest: string,
    value: bigint,
    expectedRevision: bigint,
    validFrom: bigint,
    validUntil: bigint,
    enabled: boolean,
    replace: boolean
  ] & {
    scope: string;
    digest: string;
    value: bigint;
    expectedRevision: bigint;
    validFrom: bigint;
    validUntil: bigint;
    enabled: boolean;
    replace: boolean;
  };

  export type PinStruct = {
    scope: BytesLike;
    digest: BytesLike;
    revision: BigNumberish;
  };

  export type PinStructOutput = [
    scope: string,
    digest: string,
    revision: bigint
  ] & { scope: string; digest: string; revision: bigint };

  export type StatementStruct = {
    contextDigest: BytesLike;
    transferDigest: BytesLike;
    projectionCommitment: BigNumberish;
    evaluatedAt: BigNumberish;
    validUntil: BigNumberish;
    consumer: AddressLike;
    pins: PilotCurrentRegistry.PinStruct[];
  };

  export type StatementStructOutput = [
    contextDigest: string,
    transferDigest: string,
    projectionCommitment: bigint,
    evaluatedAt: bigint,
    validUntil: bigint,
    consumer: string,
    pins: PilotCurrentRegistry.PinStructOutput[]
  ] & {
    contextDigest: string;
    transferDigest: string;
    projectionCommitment: bigint;
    evaluatedAt: bigint;
    validUntil: bigint;
    consumer: string;
    pins: PilotCurrentRegistry.PinStructOutput[];
  };
}

export interface PilotCurrentRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEFAULT_ADMIN_ROLE"
      | "INITIAL_ADMIN_DELAY"
      | "PAUSER_ROLE"
      | "acceptDefaultAdminTransfer"
      | "artifactManifestDigest"
      | "beginDefaultAdminTransfer"
      | "cancelDefaultAdminTransfer"
      | "changeDefaultAdminDelay"
      | "consumptionOwner"
      | "defaultAdmin"
      | "defaultAdminDelay"
      | "defaultAdminDelayIncreaseWait"
      | "getRoleAdmin"
      | "grantRole"
      | "hasRole"
      | "head"
      | "inspect"
      | "mirror"
      | "mirroredReceipts"
      | "owner"
      | "pause"
      | "paused"
      | "pendingDefaultAdmin"
      | "pendingDefaultAdminDelay"
      | "publishBatch"
      | "publishHead"
      | "publishStatement"
      | "publisherEpochs"
      | "publishers"
      | "renounceRole"
      | "revokeRole"
      | "rollbackDefaultAdminDelay"
      | "setPublisher"
      | "statementId"
      | "statementPublication"
      | "supportsInterface"
      | "unpause"
      | "verifier"
      | "verifierCodeHash"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AuthorizationMirrored"
      | "DefaultAdminDelayChangeCanceled"
      | "DefaultAdminDelayChangeScheduled"
      | "DefaultAdminTransferCanceled"
      | "DefaultAdminTransferScheduled"
      | "HeadPublished"
      | "Paused"
      | "PublisherChanged"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "StatementPublished"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "INITIAL_ADMIN_DELAY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PAUSER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "acceptDefaultAdminTransfer",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "artifactManifestDigest",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "beginDefaultAdminTransfer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelDefaultAdminTransfer",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "changeDefaultAdminDelay",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "consumptionOwner",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "defaultAdmin",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "defaultAdminDelay",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "defaultAdminDelayIncreaseWait",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "head",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "inspect",
    values: [
      BytesLike,
      BytesLike,
      [BigNumberish, BigNumberish],
      [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]],
      [BigNumberish, BigNumberish],
      BigNumberish[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "mirror",
    values: [
      BytesLike,
      BytesLike,
      BytesLike,
      [BigNumberish, BigNumberish],
      [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]],
      [BigNumberish, BigNumberish],
      BigNumberish[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "mirroredReceipts",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingDefaultAdmin",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "pendingDefaultAdminDelay",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "publishBatch",
    values: [
      BytesLike,
      BigNumberish,
      PilotCurrentRegistry.HeadUpdateStruct[],
      PilotCurrentRegistry.StatementStruct
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "publishHead",
    values: [
      BytesLike,
      BigNumberish,
      BytesLike,
      BytesLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      boolean
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "publishStatement",
    values: [BytesLike, PilotCurrentRegistry.StatementStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "publisherEpochs",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "publishers",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "rollbackDefaultAdminDelay",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setPublisher",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "statementId",
    values: [BytesLike, PilotCurrentRegistry.StatementStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "statementPublication",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(functionFragment: "verifier", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "verifierCodeHash",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "INITIAL_ADMIN_DELAY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PAUSER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "acceptDefaultAdminTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "artifactManifestDigest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "beginDefaultAdminTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelDefaultAdminTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "changeDefaultAdminDelay",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "consumptionOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "defaultAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "defaultAdminDelay",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "defaultAdminDelayIncreaseWait",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "head", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "inspect", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "mirror", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "mirroredReceipts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingDefaultAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pendingDefaultAdminDelay",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "publishBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "publishHead",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "publishStatement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "publisherEpochs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "publishers", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "rollbackDefaultAdminDelay",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPublisher",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "statementId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "statementPublication",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "verifier", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "verifierCodeHash",
    data: BytesLike
  ): Result;
}

export namespace AuthorizationMirroredEvent {
  export type InputTuple = [
    tenant: BytesLike,
    statementId: BytesLike,
    receiptId: BytesLike,
    nullifier: BigNumberish
  ];
  export type OutputTuple = [
    tenant: string,
    statementId: string,
    receiptId: string,
    nullifier: bigint
  ];
  export interface OutputObject {
    tenant: string;
    statementId: string;
    receiptId: string;
    nullifier: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DefaultAdminDelayChangeCanceledEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DefaultAdminDelayChangeScheduledEvent {
  export type InputTuple = [
    newDelay: BigNumberish,
    effectSchedule: BigNumberish
  ];
  export type OutputTuple = [newDelay: bigint, effectSchedule: bigint];
  export interface OutputObject {
    newDelay: bigint;
    effectSchedule: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DefaultAdminTransferCanceledEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DefaultAdminTransferScheduledEvent {
  export type InputTuple = [
    newAdmin: AddressLike,
    acceptSchedule: BigNumberish
  ];
  export type OutputTuple = [newAdmin: string, acceptSchedule: bigint];
  export interface OutputObject {
    newAdmin: string;
    acceptSchedule: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace HeadPublishedEvent {
  export type InputTuple = [
    tenant: BytesLike,
    kind: BigNumberish,
    scope: BytesLike,
    revision: BigNumberish,
    digest: BytesLike,
    value: BigNumberish,
    validFrom: BigNumberish,
    validUntil: BigNumberish,
    enabled: boolean,
    publisherEpoch: BigNumberish
  ];
  export type OutputTuple = [
    tenant: string,
    kind: bigint,
    scope: string,
    revision: bigint,
    digest: string,
    value: bigint,
    validFrom: bigint,
    validUntil: bigint,
    enabled: boolean,
    publisherEpoch: bigint
  ];
  export interface OutputObject {
    tenant: string;
    kind: bigint;
    scope: string;
    revision: bigint;
    digest: string;
    value: bigint;
    validFrom: bigint;
    validUntil: bigint;
    enabled: boolean;
    publisherEpoch: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PublisherChangedEvent {
  export type InputTuple = [
    tenant: BytesLike,
    publisher: AddressLike,
    epoch: BigNumberish
  ];
  export type OutputTuple = [tenant: string, publisher: string, epoch: bigint];
  export interface OutputObject {
    tenant: string;
    publisher: string;
    epoch: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StatementPublishedEvent {
  export type InputTuple = [
    tenant: BytesLike,
    statementId: BytesLike,
    contextDigest: BytesLike,
    consumer: AddressLike,
    projectionCommitment: BigNumberish
  ];
  export type OutputTuple = [
    tenant: string,
    statementId: string,
    contextDigest: string,
    consumer: string,
    projectionCommitment: bigint
  ];
  export interface OutputObject {
    tenant: string;
    statementId: string;
    contextDigest: string;
    consumer: string;
    projectionCommitment: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PilotCurrentRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): PilotCurrentRegistry;
  waitForDeployment(): Promise<this>;

  interface: PilotCurrentRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  INITIAL_ADMIN_DELAY: TypedContractMethod<[], [bigint], "view">;

  PAUSER_ROLE: TypedContractMethod<[], [string], "view">;

  acceptDefaultAdminTransfer: TypedContractMethod<[], [void], "nonpayable">;

  artifactManifestDigest: TypedContractMethod<[], [string], "view">;

  beginDefaultAdminTransfer: TypedContractMethod<
    [newAdmin: AddressLike],
    [void],
    "nonpayable"
  >;

  cancelDefaultAdminTransfer: TypedContractMethod<[], [void], "nonpayable">;

  changeDefaultAdminDelay: TypedContractMethod<
    [newDelay: BigNumberish],
    [void],
    "nonpayable"
  >;

  consumptionOwner: TypedContractMethod<[], [string], "view">;

  defaultAdmin: TypedContractMethod<[], [string], "view">;

  defaultAdminDelay: TypedContractMethod<[], [bigint], "view">;

  defaultAdminDelayIncreaseWait: TypedContractMethod<[], [bigint], "view">;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  head: TypedContractMethod<
    [tenant: BytesLike, kind: BigNumberish, scope: BytesLike],
    [PilotCurrentRegistry.HeadStructOutput],
    "view"
  >;

  inspect: TypedContractMethod<
    [
      tenant: BytesLike,
      id: BytesLike,
      a: [BigNumberish, BigNumberish],
      b: [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]],
      c: [BigNumberish, BigNumberish],
      signals: BigNumberish[]
    ],
    [boolean],
    "view"
  >;

  mirror: TypedContractMethod<
    [
      tenant: BytesLike,
      id: BytesLike,
      receiptId: BytesLike,
      a: [BigNumberish, BigNumberish],
      b: [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]],
      c: [BigNumberish, BigNumberish],
      signals: BigNumberish[]
    ],
    [void],
    "nonpayable"
  >;

  mirroredReceipts: TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  pendingDefaultAdmin: TypedContractMethod<
    [],
    [[string, bigint] & { newAdmin: string; schedule: bigint }],
    "view"
  >;

  pendingDefaultAdminDelay: TypedContractMethod<
    [],
    [[bigint, bigint] & { newDelay: bigint; schedule: bigint }],
    "view"
  >;

  publishBatch: TypedContractMethod<
    [
      tenant: BytesLike,
      expectedEpoch: BigNumberish,
      updates: PilotCurrentRegistry.HeadUpdateStruct[],
      statement: PilotCurrentRegistry.StatementStruct
    ],
    [string],
    "nonpayable"
  >;

  publishHead: TypedContractMethod<
    [
      tenant: BytesLike,
      kind: BigNumberish,
      scope: BytesLike,
      digest: BytesLike,
      value: BigNumberish,
      expectedRevision: BigNumberish,
      validFrom: BigNumberish,
      validUntil: BigNumberish,
      enabled: boolean
    ],
    [void],
    "nonpayable"
  >;

  publishStatement: TypedContractMethod<
    [tenant: BytesLike, statement: PilotCurrentRegistry.StatementStruct],
    [string],
    "nonpayable"
  >;

  publisherEpochs: TypedContractMethod<[arg0: BytesLike], [bigint], "view">;

  publishers: TypedContractMethod<[arg0: BytesLike], [string], "view">;

  renounceRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  rollbackDefaultAdminDelay: TypedContractMethod<[], [void], "nonpayable">;

  setPublisher: TypedContractMethod<
    [tenant: BytesLike, publisher: AddressLike],
    [void],
    "nonpayable"
  >;

  statementId: TypedContractMethod<
    [tenant: BytesLike, statement: PilotCurrentRegistry.StatementStruct],
    [string],
    "view"
  >;

  statementPublication: TypedContractMethod<
    [id: BytesLike],
    [[boolean, bigint] & { exists: boolean; epoch: bigint }],
    "view"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  verifier: TypedContractMethod<[], [string], "view">;

  verifierCodeHash: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "INITIAL_ADMIN_DELAY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PAUSER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "acceptDefaultAdminTransfer"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "artifactManifestDigest"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "beginDefaultAdminTransfer"
  ): TypedContractMethod<[newAdmin: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "cancelDefaultAdminTransfer"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "changeDefaultAdminDelay"
  ): TypedContractMethod<[newDelay: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "consumptionOwner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "defaultAdmin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "defaultAdminDelay"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "defaultAdminDelayIncreaseWait"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "head"
  ): TypedContractMethod<
    [tenant: BytesLike, kind: BigNumberish, scope: BytesLike],
    [PilotCurrentRegistry.HeadStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "inspect"
  ): TypedContractMethod<
    [
      tenant: BytesLike,
      id: BytesLike,
      a: [BigNumberish, BigNumberish],
      b: [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]],
      c: [BigNumberish, BigNumberish],
      signals: BigNumberish[]
    ],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "mirror"
  ): TypedContractMethod<
    [
      tenant: BytesLike,
      id: BytesLike,
      receiptId: BytesLike,
      a: [BigNumberish, BigNumberish],
      b: [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]],
      c: [BigNumberish, BigNumberish],
      signals: BigNumberish[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "mirroredReceipts"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "pendingDefaultAdmin"
  ): TypedContractMethod<
    [],
    [[string, bigint] & { newAdmin: string; schedule: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "pendingDefaultAdminDelay"
  ): TypedContractMethod<
    [],
    [[bigint, bigint] & { newDelay: bigint; schedule: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "publishBatch"
  ): TypedContractMethod<
    [
      tenant: BytesLike,
      expectedEpoch: BigNumberish,
      updates: PilotCurrentRegistry.HeadUpdateStruct[],
      statement: PilotCurrentRegistry.StatementStruct
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "publishHead"
  ): TypedContractMethod<
    [
      tenant: BytesLike,
      kind: BigNumberish,
      scope: BytesLike,
      digest: BytesLike,
      value: BigNumberish,
      expectedRevision: BigNumberish,
      validFrom: BigNumberish,
      validUntil: BigNumberish,
      enabled: boolean
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "publishStatement"
  ): TypedContractMethod<
    [tenant: BytesLike, statement: PilotCurrentRegistry.StatementStruct],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "publisherEpochs"
  ): TypedContractMethod<[arg0: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "publishers"
  ): TypedContractMethod<[arg0: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "rollbackDefaultAdminDelay"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPublisher"
  ): TypedContractMethod<
    [tenant: BytesLike, publisher: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "statementId"
  ): TypedContractMethod<
    [tenant: BytesLike, statement: PilotCurrentRegistry.StatementStruct],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "statementPublication"
  ): TypedContractMethod<
    [id: BytesLike],
    [[boolean, bigint] & { exists: boolean; epoch: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verifier"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "verifierCodeHash"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "AuthorizationMirrored"
  ): TypedContractEvent<
    AuthorizationMirroredEvent.InputTuple,
    AuthorizationMirroredEvent.OutputTuple,
    AuthorizationMirroredEvent.OutputObject
  >;
  getEvent(
    key: "DefaultAdminDelayChangeCanceled"
  ): TypedContractEvent<
    DefaultAdminDelayChangeCanceledEvent.InputTuple,
    DefaultAdminDelayChangeCanceledEvent.OutputTuple,
    DefaultAdminDelayChangeCanceledEvent.OutputObject
  >;
  getEvent(
    key: "DefaultAdminDelayChangeScheduled"
  ): TypedContractEvent<
    DefaultAdminDelayChangeScheduledEvent.InputTuple,
    DefaultAdminDelayChangeScheduledEvent.OutputTuple,
    DefaultAdminDelayChangeScheduledEvent.OutputObject
  >;
  getEvent(
    key: "DefaultAdminTransferCanceled"
  ): TypedContractEvent<
    DefaultAdminTransferCanceledEvent.InputTuple,
    DefaultAdminTransferCanceledEvent.OutputTuple,
    DefaultAdminTransferCanceledEvent.OutputObject
  >;
  getEvent(
    key: "DefaultAdminTransferScheduled"
  ): TypedContractEvent<
    DefaultAdminTransferScheduledEvent.InputTuple,
    DefaultAdminTransferScheduledEvent.OutputTuple,
    DefaultAdminTransferScheduledEvent.OutputObject
  >;
  getEvent(
    key: "HeadPublished"
  ): TypedContractEvent<
    HeadPublishedEvent.InputTuple,
    HeadPublishedEvent.OutputTuple,
    HeadPublishedEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "PublisherChanged"
  ): TypedContractEvent<
    PublisherChangedEvent.InputTuple,
    PublisherChangedEvent.OutputTuple,
    PublisherChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "StatementPublished"
  ): TypedContractEvent<
    StatementPublishedEvent.InputTuple,
    StatementPublishedEvent.OutputTuple,
    StatementPublishedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "AuthorizationMirrored(bytes32,bytes32,bytes32,uint256)": TypedContractEvent<
      AuthorizationMirroredEvent.InputTuple,
      AuthorizationMirroredEvent.OutputTuple,
      AuthorizationMirroredEvent.OutputObject
    >;
    AuthorizationMirrored: TypedContractEvent<
      AuthorizationMirroredEvent.InputTuple,
      AuthorizationMirroredEvent.OutputTuple,
      AuthorizationMirroredEvent.OutputObject
    >;

    "DefaultAdminDelayChangeCanceled()": TypedContractEvent<
      DefaultAdminDelayChangeCanceledEvent.InputTuple,
      DefaultAdminDelayChangeCanceledEvent.OutputTuple,
      DefaultAdminDelayChangeCanceledEvent.OutputObject
    >;
    DefaultAdminDelayChangeCanceled: TypedContractEvent<
      DefaultAdminDelayChangeCanceledEvent.InputTuple,
      DefaultAdminDelayChangeCanceledEvent.OutputTuple,
      DefaultAdminDelayChangeCanceledEvent.OutputObject
    >;

    "DefaultAdminDelayChangeScheduled(uint48,uint48)": TypedContractEvent<
      DefaultAdminDelayChangeScheduledEvent.InputTuple,
      DefaultAdminDelayChangeScheduledEvent.OutputTuple,
      DefaultAdminDelayChangeScheduledEvent.OutputObject
    >;
    DefaultAdminDelayChangeScheduled: TypedContractEvent<
      DefaultAdminDelayChangeScheduledEvent.InputTuple,
      DefaultAdminDelayChangeScheduledEvent.OutputTuple,
      DefaultAdminDelayChangeScheduledEvent.OutputObject
    >;

    "DefaultAdminTransferCanceled()": TypedContractEvent<
      DefaultAdminTransferCanceledEvent.InputTuple,
      DefaultAdminTransferCanceledEvent.OutputTuple,
      DefaultAdminTransferCanceledEvent.OutputObject
    >;
    DefaultAdminTransferCanceled: TypedContractEvent<
      DefaultAdminTransferCanceledEvent.InputTuple,
      DefaultAdminTransferCanceledEvent.OutputTuple,
      DefaultAdminTransferCanceledEvent.OutputObject
    >;

    "DefaultAdminTransferScheduled(address,uint48)": TypedContractEvent<
      DefaultAdminTransferScheduledEvent.InputTuple,
      DefaultAdminTransferScheduledEvent.OutputTuple,
      DefaultAdminTransferScheduledEvent.OutputObject
    >;
    DefaultAdminTransferScheduled: TypedContractEvent<
      DefaultAdminTransferScheduledEvent.InputTuple,
      DefaultAdminTransferScheduledEvent.OutputTuple,
      DefaultAdminTransferScheduledEvent.OutputObject
    >;

    "HeadPublished(bytes32,uint8,bytes32,uint64,bytes32,uint256,uint64,uint64,bool,uint64)": TypedContractEvent<
      HeadPublishedEvent.InputTuple,
      HeadPublishedEvent.OutputTuple,
      HeadPublishedEvent.OutputObject
    >;
    HeadPublished: TypedContractEvent<
      HeadPublishedEvent.InputTuple,
      HeadPublishedEvent.OutputTuple,
      HeadPublishedEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "PublisherChanged(bytes32,address,uint64)": TypedContractEvent<
      PublisherChangedEvent.InputTuple,
      PublisherChangedEvent.OutputTuple,
      PublisherChangedEvent.OutputObject
    >;
    PublisherChanged: TypedContractEvent<
      PublisherChangedEvent.InputTuple,
      PublisherChangedEvent.OutputTuple,
      PublisherChangedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "StatementPublished(bytes32,bytes32,bytes32,address,uint256)": TypedContractEvent<
      StatementPublishedEvent.InputTuple,
      StatementPublishedEvent.OutputTuple,
      StatementPublishedEvent.OutputObject
    >;
    StatementPublished: TypedContractEvent<
      StatementPublishedEvent.InputTuple,
      StatementPublishedEvent.OutputTuple,
      StatementPublishedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
