import { expect } from "chai";
import { ethers } from "hardhat";
import * as fs from "fs";
import * as path from "path";

describe("Groth16Verifier", function () {
  it("should verify a valid compliance proof", async function () {
    // Read proof and public signals generated by the circuit test
    const proofPath = "/tmp/clearproof_proof.json";
    const publicPath = "/tmp/clearproof_public.json";

    if (!fs.existsSync(proofPath) || !fs.existsSync(publicPath)) {
      console.log(
        "Proof files not found at /tmp/clearproof_*.json — using hardcoded values"
      );
    }

    const proof = fs.existsSync(proofPath)
      ? JSON.parse(fs.readFileSync(proofPath, "utf-8"))
      : {
          pi_a: [
            "8073921222709435687021728565040895226166720324601874996228166134859997239713",
            "21250026926575850493955798764612127336741546312913502650341026345846850015483",
            "1",
          ],
          pi_b: [
            [
              "15316175069298117144645790753102903219137181100390843428010978955699023654362",
              "13492439875076482042420295595895000234680578744588959415780712842977368804170",
            ],
            [
              "5314759809315125583597383793946467371139319384084053497719437608667363710596",
              "19481713981857858479177256065389077193051153217163245318247677728892162922414",
            ],
          ],
          pi_c: [
            "20775433742215878416115779669211868112105475476050753602416342585315294717025",
            "10902228172408724648940327734425470731823942523922651429611190462177051601323",
            "1",
          ],
        };

    const publicSignals = fs.existsSync(publicPath)
      ? JSON.parse(fs.readFileSync(publicPath, "utf-8"))
      : [
          "1",
          "0",
          "5165912880528319654224975632916389245447155966222261466225444971111963668911",
          "2679583485444090814519739490480408597587979659313135468790553999186444635148",
          "2",
          "1711670400",
          "21843",
          "3946334516594870472864654055107878340628457451312090927820290073103136770198",
          "25000",
          "300000",
          "1000000",
        ];

    // Deploy the verifier
    const Verifier = await ethers.getContractFactory("Groth16Verifier");
    const verifier = await Verifier.deploy();
    await verifier.waitForDeployment();

    // Format proof for the contract call
    // pA: [x, y]
    const pA: [bigint, bigint] = [BigInt(proof.pi_a[0]), BigInt(proof.pi_a[1])];

    // pB: [[x1, x2], [y1, y2]] — note: snarkjs outputs b in a different order
    const pB: [[bigint, bigint], [bigint, bigint]] = [
      [BigInt(proof.pi_b[0][1]), BigInt(proof.pi_b[0][0])],
      [BigInt(proof.pi_b[1][1]), BigInt(proof.pi_b[1][0])],
    ];

    // pC: [x, y]
    const pC: [bigint, bigint] = [BigInt(proof.pi_c[0]), BigInt(proof.pi_c[1])];

    // Public signals
    const pubSignals = publicSignals.map((s: string) => BigInt(s));

    // Verify the proof on-chain
    const result = await verifier.verifyProof(pA, pB, pC, pubSignals);
    expect(result).to.equal(true);
  });

  it("should reject an invalid proof", async function () {
    const Verifier = await ethers.getContractFactory("Groth16Verifier");
    const verifier = await Verifier.deploy();
    await verifier.waitForDeployment();

    // Use garbage values for the proof
    const pA: [bigint, bigint] = [BigInt(1), BigInt(2)];
    const pB: [[bigint, bigint], [bigint, bigint]] = [
      [BigInt(1), BigInt(2)],
      [BigInt(3), BigInt(4)],
    ];
    const pC: [bigint, bigint] = [BigInt(1), BigInt(2)];
    const pubSignals = Array(11).fill(BigInt(0));

    // Invalid proof should return false (the snarkjs verifier reverts on
    // invalid curve points, so we accept either false or a revert)
    try {
      const result = await verifier.verifyProof(pA, pB, pC, pubSignals);
      expect(result).to.equal(false);
    } catch {
      // Revert is also acceptable for invalid proofs
    }
  });
});

describe("ComplianceRegistry", function () {
  it("should verify and record a proof", async function () {
    const proofPath = "/tmp/clearproof_proof.json";
    const publicPath = "/tmp/clearproof_public.json";

    const proof = fs.existsSync(proofPath)
      ? JSON.parse(fs.readFileSync(proofPath, "utf-8"))
      : {
          pi_a: [
            "8073921222709435687021728565040895226166720324601874996228166134859997239713",
            "21250026926575850493955798764612127336741546312913502650341026345846850015483",
            "1",
          ],
          pi_b: [
            [
              "15316175069298117144645790753102903219137181100390843428010978955699023654362",
              "13492439875076482042420295595895000234680578744588959415780712842977368804170",
            ],
            [
              "5314759809315125583597383793946467371139319384084053497719437608667363710596",
              "19481713981857858479177256065389077193051153217163245318247677728892162922414",
            ],
          ],
          pi_c: [
            "20775433742215878416115779669211868112105475476050753602416342585315294717025",
            "10902228172408724648940327734425470731823942523922651429611190462177051601323",
            "1",
          ],
        };

    const publicSignals = fs.existsSync(publicPath)
      ? JSON.parse(fs.readFileSync(publicPath, "utf-8"))
      : [
          "1",
          "0",
          "5165912880528319654224975632916389245447155966222261466225444971111963668911",
          "2679583485444090814519739490480408597587979659313135468790553999186444635148",
          "2",
          "1711670400",
          "21843",
          "3946334516594870472864654055107878340628457451312090927820290073103136770198",
          "25000",
          "300000",
          "1000000",
        ];

    // Deploy verifier and registry
    const Verifier = await ethers.getContractFactory("Groth16Verifier");
    const verifier = await Verifier.deploy();
    await verifier.waitForDeployment();

    const Registry = await ethers.getContractFactory("ComplianceRegistry");
    const registry = await Registry.deploy(await verifier.getAddress());
    await registry.waitForDeployment();

    // Format proof
    const pA: [bigint, bigint] = [BigInt(proof.pi_a[0]), BigInt(proof.pi_a[1])];
    const pB: [[bigint, bigint], [bigint, bigint]] = [
      [BigInt(proof.pi_b[0][1]), BigInt(proof.pi_b[0][0])],
      [BigInt(proof.pi_b[1][1]), BigInt(proof.pi_b[1][0])],
    ];
    const pC: [bigint, bigint] = [BigInt(proof.pi_c[0]), BigInt(proof.pi_c[1])];
    const pubSignals = publicSignals.map((s: string) => BigInt(s));

    const transferId = ethers.id("test-transfer-001");

    // Verify and record
    const tx = await registry.verifyAndRecord(transferId, pA, pB, pC, pubSignals);
    const receipt = await tx.wait();

    // Check event was emitted
    const event = receipt?.logs.find((log: any) => {
      try {
        return registry.interface.parseLog({ topics: log.topics as string[], data: log.data });
      } catch {
        return false;
      }
    });
    expect(event).to.not.be.undefined;

    // Check proof is recorded as verified
    const isVerified = await registry.isVerified(transferId);
    expect(isVerified).to.equal(true);
  });
});
