/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as complianceRegistrySol from "./ComplianceRegistry.sol";
export { Groth16Verifier__factory } from "./Groth16Verifier__factory";
export { SanctionsOracle__factory } from "./SanctionsOracle__factory";
export { VASPRegistry__factory } from "./VASPRegistry__factory";
