/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ISanctionsRootReceiver,
  ISanctionsRootReceiverInterface,
} from "../../contracts/ISanctionsRootReceiver";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "newRoot",
        type: "bytes32",
      },
      {
        internalType: "uint32",
        name: "leafCount",
        type: "uint32",
      },
    ],
    name: "receiveRoot",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ISanctionsRootReceiver__factory {
  static readonly abi = _abi;
  static createInterface(): ISanctionsRootReceiverInterface {
    return new Interface(_abi) as ISanctionsRootReceiverInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ISanctionsRootReceiver {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as ISanctionsRootReceiver;
  }
}
