/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface VerifierRouterInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ADMIN_ROLE"
      | "DEFAULT_ADMIN_ROLE"
      | "EMERGENCY_ROLE"
      | "activateVerifier"
      | "completeRetirement"
      | "disableVerifier"
      | "getRoleAdmin"
      | "getVerifier"
      | "grantRole"
      | "hasRole"
      | "isVerifierActive"
      | "minTimelock"
      | "pause"
      | "paused"
      | "pendingRegistrations"
      | "pendingRetirements"
      | "registerVerifier"
      | "renounceRole"
      | "revokeRole"
      | "scheduleRetirement"
      | "supportsInterface"
      | "timelocks"
      | "unpause"
      | "updateTimelock"
      | "verifiers"
      | "verifyProof"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Paused"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "TimelockUpdated"
      | "Unpaused"
      | "VerifierActivated"
      | "VerifierDisabled"
      | "VerifierRegistered"
      | "VerifierRetired"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "EMERGENCY_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "activateVerifier",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "completeRetirement",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "disableVerifier",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getVerifier",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isVerifierActive",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "minTimelock",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingRegistrations",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "pendingRetirements",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerVerifier",
    values: [BytesLike, AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "scheduleRetirement",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "timelocks",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateTimelock",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "verifiers",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyProof",
    values: [
      BytesLike,
      [BigNumberish, BigNumberish],
      [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]],
      [BigNumberish, BigNumberish],
      BigNumberish[]
    ]
  ): string;

  decodeFunctionResult(functionFragment: "ADMIN_ROLE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "EMERGENCY_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "activateVerifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "completeRetirement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "disableVerifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVerifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isVerifierActive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minTimelock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingRegistrations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pendingRetirements",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerVerifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "scheduleRetirement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "timelocks", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateTimelock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "verifiers", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "verifyProof",
    data: BytesLike
  ): Result;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TimelockUpdatedEvent {
  export type InputTuple = [newTimelock: BigNumberish];
  export type OutputTuple = [newTimelock: bigint];
  export interface OutputObject {
    newTimelock: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerifierActivatedEvent {
  export type InputTuple = [selector: BytesLike, verifier: AddressLike];
  export type OutputTuple = [selector: string, verifier: string];
  export interface OutputObject {
    selector: string;
    verifier: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerifierDisabledEvent {
  export type InputTuple = [selector: BytesLike, verifier: AddressLike];
  export type OutputTuple = [selector: string, verifier: string];
  export interface OutputObject {
    selector: string;
    verifier: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerifierRegisteredEvent {
  export type InputTuple = [
    selector: BytesLike,
    verifier: AddressLike,
    name: string,
    timelock: BigNumberish
  ];
  export type OutputTuple = [
    selector: string,
    verifier: string,
    name: string,
    timelock: bigint
  ];
  export interface OutputObject {
    selector: string;
    verifier: string;
    name: string;
    timelock: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerifierRetiredEvent {
  export type InputTuple = [selector: BytesLike, verifier: AddressLike];
  export type OutputTuple = [selector: string, verifier: string];
  export interface OutputObject {
    selector: string;
    verifier: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface VerifierRouter extends BaseContract {
  connect(runner?: ContractRunner | null): VerifierRouter;
  waitForDeployment(): Promise<this>;

  interface: VerifierRouterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  EMERGENCY_ROLE: TypedContractMethod<[], [string], "view">;

  activateVerifier: TypedContractMethod<
    [selector: BytesLike, name: string],
    [void],
    "nonpayable"
  >;

  completeRetirement: TypedContractMethod<
    [selector: BytesLike],
    [void],
    "nonpayable"
  >;

  disableVerifier: TypedContractMethod<
    [selector: BytesLike],
    [void],
    "nonpayable"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  getVerifier: TypedContractMethod<[selector: BytesLike], [string], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  isVerifierActive: TypedContractMethod<
    [selector: BytesLike],
    [boolean],
    "view"
  >;

  minTimelock: TypedContractMethod<[], [bigint], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  pendingRegistrations: TypedContractMethod<
    [arg0: BytesLike],
    [string],
    "view"
  >;

  pendingRetirements: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  registerVerifier: TypedContractMethod<
    [selector: BytesLike, verifier: AddressLike, name: string],
    [void],
    "nonpayable"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  scheduleRetirement: TypedContractMethod<
    [selector: BytesLike],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  timelocks: TypedContractMethod<[arg0: BytesLike], [bigint], "view">;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  updateTimelock: TypedContractMethod<
    [newTimelock: BigNumberish],
    [void],
    "nonpayable"
  >;

  verifiers: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, bigint, boolean, string] & {
        verifier: string;
        registeredAt: bigint;
        disabledAt: bigint;
        active: boolean;
        name: string;
      }
    ],
    "view"
  >;

  verifyProof: TypedContractMethod<
    [
      selector: BytesLike,
      _pA: [BigNumberish, BigNumberish],
      _pB: [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]],
      _pC: [BigNumberish, BigNumberish],
      _pubSignals: BigNumberish[]
    ],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "EMERGENCY_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "activateVerifier"
  ): TypedContractMethod<
    [selector: BytesLike, name: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "completeRetirement"
  ): TypedContractMethod<[selector: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "disableVerifier"
  ): TypedContractMethod<[selector: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getVerifier"
  ): TypedContractMethod<[selector: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isVerifierActive"
  ): TypedContractMethod<[selector: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "minTimelock"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "pendingRegistrations"
  ): TypedContractMethod<[arg0: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "pendingRetirements"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "registerVerifier"
  ): TypedContractMethod<
    [selector: BytesLike, verifier: AddressLike, name: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "scheduleRetirement"
  ): TypedContractMethod<[selector: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "timelocks"
  ): TypedContractMethod<[arg0: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateTimelock"
  ): TypedContractMethod<[newTimelock: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verifiers"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, bigint, boolean, string] & {
        verifier: string;
        registeredAt: bigint;
        disabledAt: bigint;
        active: boolean;
        name: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "verifyProof"
  ): TypedContractMethod<
    [
      selector: BytesLike,
      _pA: [BigNumberish, BigNumberish],
      _pB: [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]],
      _pC: [BigNumberish, BigNumberish],
      _pubSignals: BigNumberish[]
    ],
    [boolean],
    "view"
  >;

  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "TimelockUpdated"
  ): TypedContractEvent<
    TimelockUpdatedEvent.InputTuple,
    TimelockUpdatedEvent.OutputTuple,
    TimelockUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;
  getEvent(
    key: "VerifierActivated"
  ): TypedContractEvent<
    VerifierActivatedEvent.InputTuple,
    VerifierActivatedEvent.OutputTuple,
    VerifierActivatedEvent.OutputObject
  >;
  getEvent(
    key: "VerifierDisabled"
  ): TypedContractEvent<
    VerifierDisabledEvent.InputTuple,
    VerifierDisabledEvent.OutputTuple,
    VerifierDisabledEvent.OutputObject
  >;
  getEvent(
    key: "VerifierRegistered"
  ): TypedContractEvent<
    VerifierRegisteredEvent.InputTuple,
    VerifierRegisteredEvent.OutputTuple,
    VerifierRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "VerifierRetired"
  ): TypedContractEvent<
    VerifierRetiredEvent.InputTuple,
    VerifierRetiredEvent.OutputTuple,
    VerifierRetiredEvent.OutputObject
  >;

  filters: {
    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "TimelockUpdated(uint256)": TypedContractEvent<
      TimelockUpdatedEvent.InputTuple,
      TimelockUpdatedEvent.OutputTuple,
      TimelockUpdatedEvent.OutputObject
    >;
    TimelockUpdated: TypedContractEvent<
      TimelockUpdatedEvent.InputTuple,
      TimelockUpdatedEvent.OutputTuple,
      TimelockUpdatedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;

    "VerifierActivated(bytes32,address)": TypedContractEvent<
      VerifierActivatedEvent.InputTuple,
      VerifierActivatedEvent.OutputTuple,
      VerifierActivatedEvent.OutputObject
    >;
    VerifierActivated: TypedContractEvent<
      VerifierActivatedEvent.InputTuple,
      VerifierActivatedEvent.OutputTuple,
      VerifierActivatedEvent.OutputObject
    >;

    "VerifierDisabled(bytes32,address)": TypedContractEvent<
      VerifierDisabledEvent.InputTuple,
      VerifierDisabledEvent.OutputTuple,
      VerifierDisabledEvent.OutputObject
    >;
    VerifierDisabled: TypedContractEvent<
      VerifierDisabledEvent.InputTuple,
      VerifierDisabledEvent.OutputTuple,
      VerifierDisabledEvent.OutputObject
    >;

    "VerifierRegistered(bytes32,address,string,uint256)": TypedContractEvent<
      VerifierRegisteredEvent.InputTuple,
      VerifierRegisteredEvent.OutputTuple,
      VerifierRegisteredEvent.OutputObject
    >;
    VerifierRegistered: TypedContractEvent<
      VerifierRegisteredEvent.InputTuple,
      VerifierRegisteredEvent.OutputTuple,
      VerifierRegisteredEvent.OutputObject
    >;

    "VerifierRetired(bytes32,address)": TypedContractEvent<
      VerifierRetiredEvent.InputTuple,
      VerifierRetiredEvent.OutputTuple,
      VerifierRetiredEvent.OutputObject
    >;
    VerifierRetired: TypedContractEvent<
      VerifierRetiredEvent.InputTuple,
      VerifierRetiredEvent.OutputTuple,
      VerifierRetiredEvent.OutputObject
    >;
  };
}
